config/routes.rb
Rails.application.routes.draw do
 
  namespace :backoffice do
    get 'admins/index'
  end
  get 'backoffice', to: 'backoffice/dashboard#index' 
  get 'admin', to: 'backoffice/dashboard#index'


  namespace :backoffice do
    resources :admins
    resources :category
    get 'categories/index'
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get '/home', to: 'home#index'
  end

  devise_for :admins
  devise_for :members
  
  root 'site/home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :member

  monetize :price_cents

   has_attached_file :picture, styles: { medium: "300x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
 enum role: {:full_acess => 0, :restricted_acess => 1}
   #0 - full acess / 1 - limited acess

  scope :using_escope, -> {where(role:1)}
  #using scope according documentation also using lambda method
  #above could be re-write as 

  # def self.using_escope
  # 	where(role:0)
  # end

  def role_br
  	if self.role == 'full_acess'
  		'Acesso Completo'
  	else
  		'Acesso Restrito'
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :description, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	layout :layout_by_resource
	  include Pundit
  	protect_from_forgery

  	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	private

	#pundit method for non authorized users
	def user_not_authorized
    flash[:alert] = "Você não tem autorização para fazer isso!"
    redirect_to(request.referrer || root_path)
  end

	# Layout per resource_name
	def layout_by_resource
	  if devise_controller? && resource_name == :admin
	    "backoffice_devise"
	  else
	    "application"
	  end
	end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < ApplicationController
	layout 'backoffice'
	before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
  	@admins = Admin.all #Using escope. Escopes in Admin model
  end

  def new
  	@admin = Admin.new
  	authorize @admin
  end

  def create
  	@admin = Admin.new(admin_params)
  	if @admin.save
  		redirect_to backoffice_admins_index_path, :notice => 'Admin criado com sucesso'
  	else
  		render 'new'
  	end
  end

  def show
  end

  def update
  	if @admin.update(admin_params)
  		AdminMailer.update_email(current_admin, @admin).deliver_now
  		redirect_to backoffice_admins_index_path, :notice => 'Admin atualizado com sucesso'
  	else
  		render 'edit'
  	end
  end

  def edit
  	authorize @admin
  end

  def destroy
  	authorize @admin
  	if @admin.destroy
  		redirect_to backoffice_admins_index_path, :notice => 'Admin excluido com sucesso'
  	else
  		render :edit
  	end
  end

  def pundit_user
  	current_admin
  end

  def admin_modal
  respond_to do |format|
    format.html
    format.js
  end
end

  private

  def admin_params
    if password_blank?
        params[:admin].delete(:password) && params[:admin].delete(:password_confirmation)
      end
  	params.require(:admin).permit(:name,:email, :password, :password_confirmation, :role)
  end

  def set_admin
  	@admin = Admin.find(params[:id])
  end

  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end


end

app/controllers/backoffice/category_controller.rb
class Backoffice::CategoryController < ApplicationController
	before_action :find_category, only: [:edit, :update]
	before_action :authenticate_admin!
	layout 'backoffice'
  
  def index
  	@categories = Category.order(:description)
  end

  def new
  	@category = Category.new
  end

  def edit
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		redirect_to backoffice_category_index_path, :notice => "Categoria #{@category.description} criada com sucesso!"
  	else
  		render'new'
  	end
  end

  def update
  	if @category.update(category_params)
  		redirect_to  backoffice_category_index_path, :notice => "Categoria #{@category.description} atualizada com sucesso!" 	
  	else
  		render 'edit'
  	end
  end	

  private

  def find_category
  	@category = Category.find(params[:id])
  end

  def category_params
  	params.require(:category).permit(:id, :description)
  end 

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
	before_action :authenticate_admin!
	layout 'backoffice'

  def index
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
	layout 'site'

  def index
  	@categories = Category.order(:description)
  	@ads = Ad.order(:title).page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
	OptionsRoles = Struct.new(:key,:value)

	def options_roles
		Admin.roles_i18n.map do |key,value|
			OptionsRoles.new(key,value)
		end
	end
end

app/helpers/backoffice/category_helper.rb
module Backoffice::CategoryHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backoffice/admins/_form.html.erb
<%= form_for [:backoffice, @admin] do |f| %>
 <div class="col-lg-6">
		<div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name, class: 'form-control' %>
	  </div>

	  <div class="field">
	    <%= f.label :email %><br />
	    <%= f.email_field :email, autofocus: true,  class:'form-control',autocomplete: "email" %>
	  </div>

	  <div class="field">
	    <%= f.label :password %>
	    <% if @minimum_password_length %>
	    	<em>(<%= @minimum_password_length %> characters minimum)</em>
	    <% end %><br />
	    <%= f.password_field :password, class:'form-control', autocomplete: "off" %>
	  </div>

	  <div class="field">
	    <%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, class:'form-control', autocomplete: "off" %>
	  </div>

	  <div class="field">
	    <%= f.label :permissão %><br />
	    <%= f.collection_select :role,options_roles,:key,:value, {prompt: " "}, {class:"form-control"} %>
	  </div>
	  <br>
	  <div class="actions">
	    <%= f.submit "Enviar", class: 'btn btn-success' %>
	  </div>
	<% end %>
</div>

app/views/backoffice/admins/_send.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admins/_sendMail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admins/edit.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">
      <h3>Editar Administrador</h3>
  </div>
<div class="panel-body">
    <div class="table-responsive">
    	<%= render :partial => 'form' %>
	  </div>
    </div>
</div>

app/views/backoffice/admins/index.html.erb
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Administradores</h3>

        <% if policy(@admins).new? %>
          <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-circle pull-right", style: "margin-top: -45px" do %>
          	<i class="fa fa-plus "></i>
          <%end%>
        <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Email</th>
                        <% if policy(@admins).edit? %>
                          <th>Permissão</th>
                          <th>Ação</th>
                        <%end%>
                    </tr>
                </thead>
                <tbody>
                	<% @admins.each do |adm| %>
                    <tr>
                      <td><%= adm.name%></td>
                      <td><%= adm.email%></td>
                      <% if policy(@admins).edit? %>
                          <td><%= adm.role_br%></td>
                          <td style="width: 150px">
                            <%= link_to '#', class:"btn btn-info btn-circle", data: {toogle: "modal", target: "#sendMailModal", modal: true}, remote: true do %>
                                  <i class="fa fa-envelope-o"></i>
                            <% end %>
                            <%= render partial: 'send' %>
                         		<%= link_to edit_backoffice_admin_path(adm), class:"btn btn-primary btn-circle" do %>
                             			<i class="fa fa-search-plus "></i>
    				              	<% end %>
                            <% if current_admin != adm %>
                              <%= link_to backoffice_admin_path(adm), method: :delete, data: {confirm: "Você tem certeza que quer apagar o administrador <b>#{adm.email}?</b>"}, class: "btn btn-danger btn-circle" do %>
                                  <i class="fa fa-trash-o "></i>
                              <% end %>
                            <% end %>
                          <%end%>
    							     </td>
                      </tr>
                  <%end%>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->

app/views/backoffice/admins/new.html.erb
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Cadastrar Administrador</h3>
         <% if @admin.errors.any? %>
            <% @admin.errors.full_messages.each do |message| %>
              <script>
                $.notify("<%= message %>", "warn");
              </script>
            <% end %>
       <% end %>
    </div>
<div class="panel-body">
    <div class="table-responsive">
    	<%= render :partial => 'form' %>
    </div>
</div>

app/views/backoffice/category/_form.html.erb
<div class="col-lg-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3> Categorias </h3>
            <% if @category.errors.any? %>
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <% @category.errors.full_messages.each do |message| %>
                  <%= message %>
                <% end %>
              </div>
           <% end %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
        	<%= form_for [:backoffice, @category] do |f| %>
        		<%= f.label :descrição_da_categoria %>
        		<%= f.text_field :description %>
        		<%= f.submit 'Alterar' %>
            <% end %>
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>

app/views/backoffice/category/edit.html.erb
<br>
<div id="wrapper">
    <!-- Page Content -->
        <div class="container-fluid">
            <div class="row">
                   <%= render partial: "form" %>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

app/views/backoffice/category/index.html.erb
<br>  
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Categorias</h3>
        <%= link_to new_backoffice_category_path, class:"btn btn-success btn-circle pull-right", style: "margin-top: -45px" do %>
        	<i class="fa fa-plus "></i>
        <%end%>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table  class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Identificador</th>
                        <th>Descrição</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                	<% @categories.each do |cat| %>
                        <tr>
                           <td><%= cat.id%></td>
                           <td><%= cat.description %> </td>
                           <td style="width: 150px">
                           		<%= link_to edit_backoffice_category_path(cat), class:"btn btn-primary btn-circle" do %>
                               			<i class="fa fa-search-plus "></i>
   							   	<% end %>
   							   <button type="button" class="btn btn-danger btn-circle" disabled="disabled"><i class="fa fa-trash-o "></i>
   							   </button>
							</td>
                    </tr>
                     <%end%>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->

app/views/backoffice/category/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
       <h3> Cadastro de Categoria </h3>
       <% if @category.errors.any? %>
            <% @category.errors.full_messages.each do |message| %>
              <script>
                $.notify("<%= message %>", "warn");
              </script>
            <% end %>
       <% end %>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-6">
                <%= form_for @category, url:  backoffice_category_index_path do |f| %>
                         <%= f.label :descrição_da_categoria %>
                         <%= f.text_field :description %>
                         <%= f.submit 'Alterar' %>
                <% end %>
            </div>
            <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
    </div>
    <!-- /.panel-body -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escambo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="modal-holder"></div>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escambo Admin </title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<%= render partial: 'layouts/backoffice_shared/backoffice_navigation' %>
    <div id="wrapper">
    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <%= yield %>   
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    
    <% if notice %>
         <script>
            $.notify("<%= notice %>", "success");
        </script>
     <% end %>
     <% if alert %>
         <script>
            $.notify("<%= alert %>", "warning");
        </script>
     <% end %>
    
</body>

</html>


                                

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

</head>

<body>
    <%= yield %>
</body>

</html>

app/views/layouts/backoffice_shared/_backoffice_navigation.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Escambo Admin | Logado como <%= current_admin.email %></a>
            </div>
            <!--/.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <%=link_to destroy_admin_session_path, method: :delete do%>
                                <i class="fa fa-sign-out fa-fw"></i> Sair
                             <% end %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group --> 
                        </li>
                        <li>
                            <%=link_to admin_path do %>
                            <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <%end%>
                        </li>
                        <li>
                            <%=link_to  backoffice_category_index_path do %>
                            <i class="fa fa-th-list "></i> Categorias
                            <%end%>
                        </li>
                        <li>
                            <%=link_to  backoffice_admins_index_path do %>
                            <i class="fa fa-users"></i> Administradores
                            <%end%>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escambo - Compre e Venda Já</title>
  </head>

  <body>
   <%= render partial: 'layouts/site_shared/site_navigation' %>
    <%= yield %>
    <%= render partial: 'layouts/site_shared/site_footer' %>
  </body>

</html>

app/views/layouts/site_shared/_site_footer.html.erb
 <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/layouts/site_shared/_site_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Escambo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/site/home/index.html.erb
        <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h1 class="my-4">Shop Name</h1>
            <div class="list-group">
            <% @categories.each do |cat| %>
              <a href="#" class="list-group-item"><%= cat.description %></a>
             <%end %>
            </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="http://www.colibri-interactive.com/themes/bold/minimal/wp-content/uploads/sites/4/2015/10/blog_3-900x350.jpg" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="http://colibri-interactive.com/themes/bold/minimal/wp-content/uploads/sites/4/2015/10/blog_4-900x350.jpg" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="http://www.liltfilms.com/wp-content/uploads/2012/11/cropped-home-office-macbookair-apple-brand-notebook-computer-top-uhd-4k-wallpapers-2880x1800-900x350.jpg" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

          <div class="row">

            <% @ads.each do |ad| %>
              <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                  <a href="#"><%= image_tag ad.picture.url(:medium) %></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="#"><%= ad.title %></a>
                    </h4>
                    <h5><%=humanized_money_with_symbol ad.price%></h5>
                    <p class="card-text"><%=truncate(ad.description, length: 40)%></p>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                  </div>
                </div>
              </div>
            <% end %>

          </div>
          <!-- /.row -->
          <div style="align-content: center">
            <%= paginate @ads %>
          </div>
          
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>